"""
dashboard.py
============
Football AI Analytics Dashboard
================================
Presentation layer only — zero modifications to the AI/tracking pipeline.

Run:
    streamlit run dashboard.py

Requires: match_stats.csv and possession_stats.csv (generated by export_data.py)
Install:  pip install streamlit plotly pandas seaborn matplotlib fpdf2
"""

import os
import io
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# ──────────────────────────────────────────────────────────────────────────────
# PAGE CONFIG
# ──────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Football AI Analytics",
    page_icon="⚽",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ──────────────────────────────────────────────────────────────────────────────
# GLOBAL THEME COLOURS
# ──────────────────────────────────────────────────────────────────────────────
TEAM_COLOURS = {
    "Team 1": "#00C9FF",   # sky blue
    "Team 2": "#FF6B35",   # orange-red
}
PITCH_GREEN  = "#1a4731"
PITCH_LINE   = "#ffffff"
BG_DARK      = "#0d1117"
BG_CARD      = "#161b22"
TEXT_PRIMARY = "#e6edf3"
TEXT_DIM     = "#8b949e"
ACCENT       = "#00C9FF"

# ──────────────────────────────────────────────────────────────────────────────
# CSS INJECTION
# ──────────────────────────────────────────────────────────────────────────────
st.markdown(f"""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600&display=swap');

  html, body, [class*="css"] {{
      font-family: 'DM Sans', sans-serif;
      background-color: {BG_DARK};
      color: {TEXT_PRIMARY};
  }}

  /* Sidebar */
  section[data-testid="stSidebar"] {{
      background-color: {BG_CARD} !important;
      border-right: 1px solid #30363d;
  }}
  section[data-testid="stSidebar"] * {{
      color: {TEXT_PRIMARY} !important;
  }}

  /* Metric cards */
  div[data-testid="metric-container"] {{
      background: {BG_CARD};
      border: 1px solid #30363d;
      border-radius: 10px;
      padding: 16px 20px;
  }}
  div[data-testid="metric-container"] label {{
      color: {TEXT_DIM} !important;
      font-size: 12px !important;
      letter-spacing: 0.08em;
      text-transform: uppercase;
  }}
  div[data-testid="metric-container"] div[data-testid="stMetricValue"] {{
      font-family: 'Bebas Neue', sans-serif;
      font-size: 2.2rem !important;
      color: {ACCENT} !important;
  }}

  /* Section headings */
  .section-title {{
      font-family: 'Bebas Neue', sans-serif;
      font-size: 1.7rem;
      letter-spacing: 0.1em;
      color: {TEXT_PRIMARY};
      border-left: 4px solid {ACCENT};
      padding-left: 12px;
      margin: 28px 0 12px 0;
  }}

  /* Chart containers */
  div[data-testid="stPlotlyChart"],
  div[data-testid="stPyplotGlobalUse"] {{
      background: {BG_CARD};
      border: 1px solid #30363d;
      border-radius: 10px;
      padding: 8px;
  }}

  /* Tabs */
  div[data-baseweb="tab-list"] {{
      background: {BG_CARD};
      border-radius: 8px;
      gap: 4px;
  }}
  button[data-baseweb="tab"] {{
      color: {TEXT_DIM} !important;
      font-weight: 500;
  }}
  button[data-baseweb="tab"][aria-selected="true"] {{
      color: {ACCENT} !important;
      background: {BG_DARK} !important;
  }}

  /* Table */
  .stDataFrame {{ border-radius: 8px; overflow: hidden; }}

  /* Divider */
  hr {{ border-color: #30363d !important; margin: 4px 0; }}

  /* Download button */
  div.stDownloadButton button {{
      background: {ACCENT} !important;
      color: #000 !important;
      font-weight: 600;
      border-radius: 6px;
      border: none;
  }}

  /* Page title */
  .dash-title {{
      font-family: 'Bebas Neue', sans-serif;
      font-size: 3.2rem;
      letter-spacing: 0.12em;
      line-height: 1;
      color: {TEXT_PRIMARY};
  }}
  .dash-subtitle {{
      color: {TEXT_DIM};
      font-size: 0.88rem;
      margin-top: 4px;
  }}
</style>
""", unsafe_allow_html=True)

# ──────────────────────────────────────────────────────────────────────────────
# PLOTLY DARK TEMPLATE
# ──────────────────────────────────────────────────────────────────────────────
PLOTLY_LAYOUT = dict(
    paper_bgcolor=BG_CARD,
    plot_bgcolor=BG_DARK,
    font=dict(family="DM Sans", color=TEXT_PRIMARY),
    margin=dict(l=16, r=16, t=36, b=16),
    colorway=[TEAM_COLOURS["Team 1"], TEAM_COLOURS["Team 2"]],
    legend=dict(bgcolor="rgba(0,0,0,0)", bordercolor="#30363d"),
    xaxis=dict(gridcolor="#21262d", linecolor="#30363d"),
    yaxis=dict(gridcolor="#21262d", linecolor="#30363d"),
)

# ──────────────────────────────────────────────────────────────────────────────
# DATA LOADING
# ──────────────────────────────────────────────────────────────────────────────
DEMO_MODE = False

@st.cache_data
def load_data():
    global DEMO_MODE
    if os.path.exists("match_stats.csv") and os.path.exists("possession_stats.csv"):
        df  = pd.read_csv("match_stats.csv")
        pos = pd.read_csv("possession_stats.csv")
        # Normalise column names
        if "team_label" not in df.columns and "team" in df.columns:
            df["team_label"] = df["team"].apply(
                lambda x: f"Team {x}" if str(x).isdigit() else str(x))
        return df, pos, False

    # ── DEMO / SYNTHETIC DATA ─────────────────────────────────────
    DEMO_MODE = True
    rng   = np.random.default_rng(42)
    FRAMES = 1800  # ~60 s @ 30 fps
    rows   = []
    for pid in range(1, 23):
        team = 1 if pid <= 11 else 2
        # Realistic positional bounds per team
        x_base = rng.uniform(5,  55) if team == 1 else rng.uniform(50, 100)
        y_base = rng.uniform(5,  63)
        x = np.clip(x_base + rng.normal(0, 8,  FRAMES), 0, 105)
        y = np.clip(y_base + rng.normal(0, 6,  FRAMES), 0, 68)
        # Speed: occasional sprints
        speed_base = rng.uniform(6, 11)
        speed = np.abs(rng.normal(speed_base, 3, FRAMES))
        speed = np.clip(speed, 0, 32)
        dist  = np.cumsum(speed / 30)   # approx distance per frame
        for f in range(FRAMES):
            rows.append({
                "frame":     f,
                "player_id": pid,
                "team":      team,
                "team_label": f"Team {team}",
                "x_px":      x[f] * 7.5,
                "y_px":      y[f] * 7.5,
                "x_m":       round(x[f], 3),
                "y_m":       round(y[f], 3),
                "speed":     round(speed[f], 2),
                "distance":  round(dist[f],  3),
            })

    df  = pd.DataFrame(rows)
    pos = pd.DataFrame({
        "team":   ["Team 1", "Team 2"],
        "frames": [int(FRAMES * 0.52), int(FRAMES * 0.48)],
    })
    return df, pos, True


df, pos_df, is_demo = load_data()

if is_demo:
    st.warning("⚠️  **Demo Mode** — showing synthetic data. "
               "Run `python export_data.py` after processing your video to load real match data.",
               icon="🔵")

# ──────────────────────────────────────────────────────────────────────────────
# SIDEBAR
# ──────────────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("<div style='font-family:Bebas Neue;font-size:1.6rem;letter-spacing:0.1em;'>⚽ Match Controls</div>",
                unsafe_allow_html=True)
    st.markdown("---")

    teams = sorted(df["team_label"].dropna().unique().tolist())
    sel_team = st.selectbox("Select Team", teams)

    team_df = df[df["team_label"] == sel_team]
    players  = sorted(team_df["player_id"].unique().tolist())
    sel_player = st.selectbox("Select Player ID", players)

    player_df = team_df[team_df["player_id"] == sel_player]

    st.markdown("---")
    st.markdown("**Frame Range (Match Timeline)**")
    max_frame = int(df["frame"].max())
    frame_range = st.slider("Frames", 0, max_frame, (0, max_frame), step=max(1, max_frame // 100))

    st.markdown("---")
    # Sprint threshold
    sprint_thresh = st.slider("Sprint Speed Threshold (km/h)", 10, 25, 17)

    st.markdown("---")
    st.caption("Football AI Analytics Dashboard")
    st.caption("Presentation layer only — AI pipeline unchanged")

# Apply frame range filter
df_range    = df[(df["frame"] >= frame_range[0]) & (df["frame"] <= frame_range[1])]
team_r      = df_range[df_range["team_label"] == sel_team]
player_r    = team_r[team_r["player_id"] == sel_player]

# ──────────────────────────────────────────────────────────────────────────────
# HEADER
# ──────────────────────────────────────────────────────────────────────────────
c_logo, c_title = st.columns([1, 9])
with c_title:
    st.markdown(f'<div class="dash-title">⚽ Football AI Analytics</div>', unsafe_allow_html=True)
    st.markdown(f'<div class="dash-subtitle">Match Performance Dashboard &nbsp;·&nbsp; '
                f'Frame {frame_range[0]}–{frame_range[1]} '
                f'({frame_range[1]-frame_range[0]+1:,} frames selected)</div>',
                unsafe_allow_html=True)

st.markdown("---")

# ──────────────────────────────────────────────────────────────────────────────
# TAB LAYOUT
# ──────────────────────────────────────────────────────────────────────────────
tab_overview, tab_player, tab_tactical, tab_report = st.tabs([
    "📊  Team Overview",
    "🏃  Player Analytics",
    "🗺️  Tactical Map",
    "📄  Export Report",
])

# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 ── TEAM OVERVIEW
# ══════════════════════════════════════════════════════════════════════════════
with tab_overview:

    # ── KPI Row ────────────────────────────────────────────────────────────
    st.markdown('<div class="section-title">Team KPIs</div>', unsafe_allow_html=True)
    k1, k2, k3, k4, k5 = st.columns(5)

    total_frames = pos_df["frames"].sum() or 1
    team_pos_row = pos_df[pos_df["team"] == sel_team]
    team_frames  = int(team_pos_row["frames"].sum()) if not team_pos_row.empty else 0
    possession_pct = team_frames / total_frames * 100

    k1.metric("Possession",     f"{possession_pct:.1f}%")
    k2.metric("Total Distance", f"{team_r['distance'].sum():,.0f} m")
    k3.metric("Avg Speed",      f"{team_r['speed'].mean():.1f} km/h")
    k4.metric("Max Speed",      f"{team_r['speed'].max():.1f} km/h")
    sprints_team = int((team_r["speed"] > sprint_thresh).sum())
    k5.metric("Sprint Frames",  f"{sprints_team:,}")

    st.markdown("---")

    # ── Possession Donut + Distance Bar ───────────────────────────────────
    c_donut, c_dist = st.columns(2)

    with c_donut:
        st.markdown('<div class="section-title">Ball Possession</div>', unsafe_allow_html=True)
        fig_pos = go.Figure(go.Pie(
            labels=pos_df["team"],
            values=pos_df["frames"],
            hole=0.55,
            marker_colors=[TEAM_COLOURS.get(t, ACCENT) for t in pos_df["team"]],
            textinfo="percent+label",
            textfont_size=13,
        ))
        fig_pos.update_layout(**PLOTLY_LAYOUT, title="Overall Ball Control Split", height=340)
        st.plotly_chart(fig_pos, use_container_width=True)

    with c_dist:
        st.markdown('<div class="section-title">Distance Covered</div>', unsafe_allow_html=True)
        team_dist = df_range.groupby("team_label")["distance"].sum().reset_index()
        fig_dist = px.bar(
            team_dist, x="team_label", y="distance",
            color="team_label",
            color_discrete_map=TEAM_COLOURS,
            labels={"team_label": "Team", "distance": "Distance (m)"},
            text_auto=".0f",
        )
        fig_dist.update_layout(**PLOTLY_LAYOUT, title="Total Distance by Team", height=340,
                                showlegend=False)
        st.plotly_chart(fig_dist, use_container_width=True)

    # ── Speed Zone Distribution ────────────────────────────────────────────
    st.markdown('<div class="section-title">Speed Zone Distribution</div>', unsafe_allow_html=True)

    def speed_zone(s):
        if s < 7:   return "Walking (<7)"
        if s < 14:  return "Jogging (7-14)"
        if s < sprint_thresh: return f"Running (14-{sprint_thresh})"
        return f"Sprinting (>{sprint_thresh})"

    ZONE_ORDER = ["Walking (<7)", "Jogging (7-14)",
                  f"Running (14-{sprint_thresh})", f"Sprinting (>{sprint_thresh})"]

    zones = df_range.copy()
    zones["zone"] = zones["speed"].apply(speed_zone)
    zone_counts = zones.groupby(["team_label", "zone"]).size().reset_index(name="count")

    fig_zones = px.bar(
        zone_counts, x="zone", y="count",
        color="team_label",
        barmode="group",
        color_discrete_map=TEAM_COLOURS,
        category_orders={"zone": ZONE_ORDER},
        labels={"zone": "Speed Zone", "count": "Frames", "team_label": "Team"},
    )
    fig_zones.update_layout(**PLOTLY_LAYOUT, title="Time Spent in Each Speed Zone", height=320)
    st.plotly_chart(fig_zones, use_container_width=True)

    # ── Player Leaderboard ────────────────────────────────────────────────
    st.markdown('<div class="section-title">Player Leaderboard</div>', unsafe_allow_html=True)

    lb = df_range.groupby(["team_label", "player_id"]).agg(
        dist_m=("distance", "sum"),
        avg_spd=("speed", "mean"),
        max_spd=("speed", "max"),
        sprints=("speed", lambda x: (x > sprint_thresh).sum()),
    ).reset_index()
    lb.columns = ["Team", "Player ID", "Distance (m)", "Avg Speed (km/h)", "Max Speed (km/h)", "Sprint Frames"]
    lb["Distance (m)"]     = lb["Distance (m)"].round(1)
    lb["Avg Speed (km/h)"] = lb["Avg Speed (km/h)"].round(2)
    lb["Max Speed (km/h)"] = lb["Max Speed (km/h)"].round(2)
    lb = lb.sort_values("Distance (m)", ascending=False).reset_index(drop=True)

    st.dataframe(
        lb.style.background_gradient(subset=["Distance (m)"], cmap="Blues")
               .background_gradient(subset=["Max Speed (km/h)"], cmap="Oranges"),
        use_container_width=True, height=360,
    )


# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 ── PLAYER ANALYTICS
# ══════════════════════════════════════════════════════════════════════════════
with tab_player:

    st.markdown(f'<div class="section-title">Player {sel_player} — {sel_team}</div>',
                unsafe_allow_html=True)

    # ── KPIs ──────────────────────────────────────────────────────────────
    pk1, pk2, pk3, pk4, pk5 = st.columns(5)
    pk1.metric("Distance",     f"{player_r['distance'].sum():,.0f} m")
    pk2.metric("Avg Speed",    f"{player_r['speed'].mean():.1f} km/h")
    pk3.metric("Max Speed",    f"{player_r['speed'].max():.1f} km/h")
    sprints_p = int((player_r["speed"] > sprint_thresh).sum())
    pk4.metric("Sprint Frames", f"{sprints_p:,}")
    # Sprint %, rough
    pk5.metric("Sprint %", f"{sprints_p / max(len(player_r), 1) * 100:.1f}%")

    st.markdown("---")
    sc_speed, sc_hist = st.columns(2)

    # ── Speed Timeline ────────────────────────────────────────────────────
    with sc_speed:
        st.markdown('<div class="section-title">Speed Timeline</div>', unsafe_allow_html=True)
        # Downsample for performance
        step = max(1, len(player_r) // 800)
        pr_ds = player_r.iloc[::step]
        fig_speed = go.Figure()
        fig_speed.add_trace(go.Scatter(
            x=pr_ds["frame"], y=pr_ds["speed"],
            mode="lines", name="Speed",
            line=dict(color=TEAM_COLOURS.get(sel_team, ACCENT), width=1.5),
            fill="tozeroy", fillcolor=f"rgba(0,201,255,0.12)",
        ))
        fig_speed.add_hline(y=sprint_thresh, line_dash="dash",
                            line_color="#ff6b35", annotation_text=f"Sprint >{sprint_thresh} km/h")
        fig_speed.update_layout(**PLOTLY_LAYOUT,
                                 title=f"Speed over Match — Player {sel_player}",
                                 xaxis_title="Frame", yaxis_title="Speed (km/h)", height=340)
        st.plotly_chart(fig_speed, use_container_width=True)

    # ── Speed Histogram ───────────────────────────────────────────────────
    with sc_hist:
        st.markdown('<div class="section-title">Speed Distribution</div>', unsafe_allow_html=True)
        fig_hist = px.histogram(
            player_r, x="speed", nbins=30,
            color_discrete_sequence=[TEAM_COLOURS.get(sel_team, ACCENT)],
            labels={"speed": "Speed (km/h)", "count": "Frames"},
        )
        fig_hist.add_vline(x=sprint_thresh, line_dash="dash", line_color="#ff6b35",
                           annotation_text="Sprint threshold")
        fig_hist.update_layout(**PLOTLY_LAYOUT, title="Time Spent at Each Speed", height=340)
        st.plotly_chart(fig_hist, use_container_width=True)

    # ── Radar Chart: Player vs Team Average ───────────────────────────────
    st.markdown('<div class="section-title">Player vs Team Radar</div>', unsafe_allow_html=True)
    rc1, rc2 = st.columns([1, 2])

    def radar_data(source_df):
        total_frames = max(len(source_df), 1)
        return {
            "Distance (norm)": source_df["distance"].sum() / 1000,
            "Avg Speed":       source_df["speed"].mean(),
            "Max Speed":       source_df["speed"].max() / 3,
            "Sprint %":        (source_df["speed"] > sprint_thresh).sum() / total_frames * 10,
            "Work Rate":       source_df["speed"].std(),
        }

    pdata = radar_data(player_r)
    tdata = radar_data(team_r)

    cats   = list(pdata.keys())
    p_vals = list(pdata.values())
    t_vals = list(tdata.values())

    fig_radar = go.Figure()
    fig_radar.add_trace(go.Scatterpolar(
        r=p_vals + [p_vals[0]], theta=cats + [cats[0]],
        name=f"Player {sel_player}",
        line_color=TEAM_COLOURS.get(sel_team, ACCENT),
        fill="toself", fillcolor=f"rgba(0,201,255,0.15)",
    ))
    fig_radar.add_trace(go.Scatterpolar(
        r=t_vals + [t_vals[0]], theta=cats + [cats[0]],
        name=f"{sel_team} Avg",
        line_color="#ff6b35",
        fill="toself", fillcolor="rgba(255,107,53,0.12)",
    ))
    fig_radar.update_layout(
        **PLOTLY_LAYOUT,
        polar=dict(
            bgcolor=BG_DARK,
            radialaxis=dict(visible=True, color=TEXT_DIM),
            angularaxis=dict(color=TEXT_PRIMARY),
        ),
        title=f"Player {sel_player} vs {sel_team} Average",
        height=420,
    )

    with rc1:
        # Summary table
        summary_tbl = pd.DataFrame({
            "Metric": cats,
            f"Player {sel_player}": [f"{v:.2f}" for v in p_vals],
            f"{sel_team} Avg":      [f"{v:.2f}" for v in t_vals],
        })
        st.dataframe(summary_tbl, use_container_width=True, hide_index=True)
    with rc2:
        st.plotly_chart(fig_radar, use_container_width=True)

    # ── Distance Over Time ────────────────────────────────────────────────
    st.markdown('<div class="section-title">Cumulative Distance</div>', unsafe_allow_html=True)
    pr_sorted = player_r.sort_values("frame")
    pr_sorted = pr_sorted.iloc[::max(1, len(pr_sorted)//800)]

    fig_dist_line = px.area(
        pr_sorted, x="frame", y="distance",
        color_discrete_sequence=[TEAM_COLOURS.get(sel_team, ACCENT)],
        labels={"frame": "Frame", "distance": "Distance (m)"},
    )
    fig_dist_line.update_layout(**PLOTLY_LAYOUT,
                                 title=f"Cumulative Distance — Player {sel_player}", height=280)
    st.plotly_chart(fig_dist_line, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 ── TACTICAL MAP
# ══════════════════════════════════════════════════════════════════════════════
with tab_tactical:

    # ── Heatmap ────────────────────────────────────────────────────────────
    st.markdown('<div class="section-title">Player Heatmap</div>', unsafe_allow_html=True)
    hm1, hm2 = st.columns([2, 1])

    with hm1:
        fig_hm, ax_hm = plt.subplots(figsize=(10, 6.5))
        ax_hm.set_facecolor(PITCH_GREEN)
        fig_hm.patch.set_facecolor(BG_CARD)

        # Draw pitch markings
        def draw_pitch(ax):
            rect = patches.Rectangle((0, 0), 105, 68, linewidth=2,
                                      edgecolor=PITCH_LINE, facecolor="none")
            ax.add_patch(rect)
            # Halfway line
            ax.plot([52.5, 52.5], [0, 68], color=PITCH_LINE, lw=1.5)
            # Centre circle
            circle = plt.Circle((52.5, 34), 9.15, color=PITCH_LINE, fill=False, lw=1.5)
            ax.add_patch(circle)
            ax.plot(52.5, 34, 'o', color=PITCH_LINE, ms=3)
            # Penalty areas
            for x0, x1 in [(0, 16.5), (88.5, 105)]:
                ax.add_patch(patches.Rectangle(
                    (x0, 13.84), abs(x1-x0), 40.32,
                    linewidth=1.5, edgecolor=PITCH_LINE, facecolor="none"))
            ax.set_xlim(-2, 107); ax.set_ylim(-2, 70)
            ax.axis("off")

        draw_pitch(ax_hm)

        if len(player_r) > 5:
            try:
                sns.kdeplot(
                    data=player_r, x="x_m", y="y_m",
                    fill=True, cmap="RdYlGn_r", alpha=0.65, levels=12, ax=ax_hm,
                    bw_adjust=0.6,
                )
            except Exception:
                ax_hm.scatter(player_r["x_m"], player_r["y_m"],
                              alpha=0.3, c=ACCENT, s=2)

        ax_hm.set_title(f"Player {sel_player} — Position Heatmap",
                        color=TEXT_PRIMARY, fontsize=12, pad=10)
        st.pyplot(fig_hm)

    with hm2:
        st.markdown("**Position Statistics**")
        if len(player_r):
            avg_x = player_r["x_m"].mean()
            avg_y = player_r["y_m"].mean()
            side  = "Own Half" if avg_x < 52.5 else "Opposition Half"
            st.metric("Avg X (m)", f"{avg_x:.1f}")
            st.metric("Avg Y (m)", f"{avg_y:.1f}")
            st.metric("Dominant Zone", side)
            st.metric("Frames Tracked", f"{len(player_r):,}")
        else:
            st.info("No data for this player in the selected range.")

    st.markdown("---")

    # ── Interactive Pitch Map ──────────────────────────────────────────────
    st.markdown('<div class="section-title">Live Pitch Map</div>', unsafe_allow_html=True)
    frame_idx = st.slider("Scrub Match Timeline (Frame)", 0, max_frame,
                           (frame_range[0] + frame_range[1]) // 2)
    frame_data = df[df["frame"] == frame_idx]

    fig_pitch = go.Figure()

    for team in sorted(frame_data["team_label"].unique()):
        td = frame_data[frame_data["team_label"] == team]
        fig_pitch.add_trace(go.Scatter(
            x=td["x_m"], y=td["y_m"],
            mode="markers+text",
            marker=dict(size=14, color=TEAM_COLOURS.get(team, "#aaa"),
                        line=dict(width=2, color="white")),
            text=td["player_id"].astype(str),
            textposition="top center",
            textfont=dict(color="white", size=10),
            name=team,
            hovertemplate="<b>%{text}</b><br>x: %{x:.1f} m<br>y: %{y:.1f} m<extra></extra>",
        ))

    # Pitch lines in Plotly
    def pitch_shapes():
        shapes = [
            dict(type="rect",  x0=0, y0=0,  x1=105, y1=68,  line=dict(color="white", width=2)),
            dict(type="line",  x0=52.5, y0=0, x1=52.5, y1=68, line=dict(color="white")),
            dict(type="circle",x0=43.35, y0=24.85, x1=61.65, y1=43.15, line=dict(color="white")),
            dict(type="rect",  x0=0,    y0=13.84, x1=16.5,  y1=54.16, line=dict(color="white")),
            dict(type="rect",  x0=88.5, y0=13.84, x1=105,   y1=54.16, line=dict(color="white")),
        ]
        return shapes

    fig_pitch.update_layout(
        **PLOTLY_LAYOUT,
        shapes=pitch_shapes(),
        xaxis=dict(range=[-3, 108], showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(range=[-3, 71],  showgrid=False, zeroline=False, showticklabels=False,
                   scaleanchor="x", scaleratio=1),
        plot_bgcolor=PITCH_GREEN,
        title=f"Player Positions — Frame {frame_idx}",
        height=520,
    )
    st.plotly_chart(fig_pitch, use_container_width=True)

    # ── Zone Filter ───────────────────────────────────────────────────────
    st.markdown('<div class="section-title">Zone Filter</div>', unsafe_allow_html=True)
    zc1, zc2, zc3 = st.columns(3)
    z_x    = zc1.number_input("Centre X (m)", 0.0, 105.0, 52.5)
    z_y    = zc2.number_input("Centre Y (m)", 0.0, 68.0,  34.0)
    z_r    = zc3.number_input("Radius (m)",   1.0, 40.0,  10.0)

    near = frame_data[
        np.sqrt((frame_data["x_m"] - z_x)**2 + (frame_data["y_m"] - z_y)**2) <= z_r
    ][["player_id", "team_label", "speed"]].rename(
        columns={"team_label": "Team", "player_id": "Player", "speed": "Speed (km/h)"}
    )
    st.write(f"**{len(near)} player(s)** within {z_r:.0f} m of ({z_x:.0f}, {z_y:.0f})")
    if len(near):
        st.dataframe(near.reset_index(drop=True), use_container_width=True)
    else:
        st.info("No players in this zone at the selected frame.")

    # ── All-player paths (selected player) ───────────────────────────────
    st.markdown('<div class="section-title">Movement Trail</div>', unsafe_allow_html=True)
    trail_step = max(1, len(player_r) // 600)
    trail_df   = player_r.sort_values("frame").iloc[::trail_step]

    fig_trail = go.Figure()
    fig_trail.add_trace(go.Scatter(
        x=trail_df["x_m"], y=trail_df["y_m"],
        mode="lines+markers",
        marker=dict(size=4, color=trail_df["speed"],
                    colorscale="RdYlGn_r", showscale=True,
                    colorbar=dict(title="Speed (km/h)", tickfont=dict(color=TEXT_DIM))),
        line=dict(color="rgba(255,255,255,0.3)", width=1),
        name=f"Player {sel_player}",
        hovertemplate="Frame %{customdata}<br>Speed: %{marker.color:.1f} km/h<extra></extra>",
        customdata=trail_df["frame"],
    ))
    fig_trail.update_layout(
        **PLOTLY_LAYOUT,
        shapes=pitch_shapes(),
        xaxis=dict(range=[-3, 108], showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(range=[-3, 71],  showgrid=False, zeroline=False, showticklabels=False,
                   scaleanchor="x", scaleratio=1),
        plot_bgcolor=PITCH_GREEN,
        title=f"Movement Trail — Player {sel_player} (colour = speed)",
        height=500,
    )
    st.plotly_chart(fig_trail, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 4 ── EXPORT REPORT
# ══════════════════════════════════════════════════════════════════════════════
with tab_report:
    st.markdown('<div class="section-title">Generate Match Report</div>', unsafe_allow_html=True)
    st.write("Export a formatted PDF report summarising team and player statistics "
             "for the selected frame range.")

    col_gen, _ = st.columns([1, 2])
    with col_gen:
        if st.button("⬇️  Generate PDF Report", type="primary"):
            try:
                from fpdf import FPDF

                class MatchReport(FPDF):
                    def header(self):
                        self.set_fill_color(13, 17, 23)
                        self.rect(0, 0, 210, 297, 'F')
                        self.set_font("Helvetica", "B", 20)
                        self.set_text_color(0, 201, 255)
                        self.cell(0, 14, "MATCH ANALYSIS REPORT", align="C", ln=True)
                        self.set_font("Helvetica", "", 9)
                        self.set_text_color(139, 148, 158)
                        self.cell(0, 6, f"Frames {frame_range[0]}–{frame_range[1]}  |  Football AI Analytics Dashboard",
                                  align="C", ln=True)
                        self.ln(4)

                    def section_title(self, title):
                        self.set_font("Helvetica", "B", 12)
                        self.set_text_color(0, 201, 255)
                        self.cell(0, 10, title, ln=True)
                        self.set_draw_color(0, 201, 255)
                        self.line(self.get_x(), self.get_y(), self.get_x() + 180, self.get_y())
                        self.ln(2)

                    def body_text(self, text):
                        self.set_font("Helvetica", "", 10)
                        self.set_text_color(230, 237, 243)
                        self.multi_cell(0, 7, text)

                    def table_header(self, cols, widths):
                        self.set_font("Helvetica", "B", 9)
                        self.set_fill_color(22, 27, 34)
                        self.set_text_color(139, 148, 158)
                        for col, w in zip(cols, widths):
                            self.cell(w, 8, col, border=1, fill=True)
                        self.ln()

                    def table_row(self, vals, widths):
                        self.set_font("Helvetica", "", 9)
                        self.set_text_color(230, 237, 243)
                        self.set_fill_color(13, 17, 23)
                        for v, w in zip(vals, widths):
                            self.cell(w, 7, str(v), border=1, fill=True)
                        self.ln()

                pdf = MatchReport()
                pdf.set_auto_page_break(True, 15)
                pdf.add_page()

                # ── Possession ────────────────────────────────────────────
                pdf.section_title("1. Team Possession")
                total_f = pos_df["frames"].sum() or 1
                for _, row in pos_df.iterrows():
                    pct = row["frames"] / total_f * 100
                    pdf.body_text(f"  {row['team']}:  {pct:.1f}%  ({row['frames']:,} frames)")
                pdf.ln(4)

                # ── Team Summary ──────────────────────────────────────────
                pdf.section_title("2. Team Performance Summary")
                team_sum = df_range.groupby("team_label").agg(
                    total_dist=("distance", "sum"),
                    avg_spd=("speed", "mean"),
                    max_spd=("speed", "max"),
                ).reset_index()

                pdf.table_header(["Team", "Distance (m)", "Avg Speed", "Max Speed"],
                                  [50, 45, 45, 45])
                for _, r in team_sum.iterrows():
                    pdf.table_row([
                        r["team_label"],
                        f"{r['total_dist']:.0f}",
                        f"{r['avg_spd']:.2f} km/h",
                        f"{r['max_spd']:.2f} km/h",
                    ], [50, 45, 45, 45])
                pdf.ln(6)

                # ── Player Stats ──────────────────────────────────────────
                pdf.section_title("3. Individual Player Metrics")
                lb2 = df_range.groupby(["team_label", "player_id"]).agg(
                    dist=("distance", "sum"),
                    avg_s=("speed", "mean"),
                    max_s=("speed", "max"),
                    spr=("speed", lambda x: (x > sprint_thresh).sum()),
                ).reset_index()
                lb2 = lb2.sort_values(["team_label", "dist"], ascending=[True, False])

                pdf.table_header(["Player", "Team", "Dist (m)", "Avg Spd", "Max Spd", "Sprints"],
                                  [22, 35, 30, 28, 28, 25])
                for _, r in lb2.iterrows():
                    pdf.table_row([
                        int(r["player_id"]), r["team_label"],
                        f"{r['dist']:.0f}",
                        f"{r['avg_s']:.1f}",
                        f"{r['max_s']:.1f}",
                        int(r["spr"]),
                    ], [22, 35, 30, 28, 28, 25])

                pdf_bytes = bytes(pdf.output())
                st.download_button(
                    label="📥  Download PDF",
                    data=pdf_bytes,
                    file_name="match_report.pdf",
                    mime="application/pdf",
                )
                st.success("Report ready! Click 'Download PDF' above.")

            except ImportError:
                st.error("fpdf2 is not installed. Run: `pip install fpdf2`")
            except Exception as e:
                st.error(f"Report generation failed: {e}")

    st.markdown("---")
    st.markdown('<div class="section-title">Export Raw Data</div>', unsafe_allow_html=True)
    dl1, dl2 = st.columns(2)

    csv_stats = df_range.to_csv(index=False).encode()
    dl1.download_button("📥  Download match_stats.csv (filtered)",
                         data=csv_stats,
                         file_name="match_stats_filtered.csv",
                         mime="text/csv")

    csv_poss = pos_df.to_csv(index=False).encode()
    dl2.download_button("📥  Download possession_stats.csv",
                         data=csv_poss,
                         file_name="possession_stats.csv",
                         mime="text/csv")

# ──────────────────────────────────────────────────────────────────────────────
# FOOTER
# ──────────────────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown(
    f"<div style='text-align:center;color:{TEXT_DIM};font-size:0.8rem;'>"
    "Football AI Analytics Dashboard &nbsp;·&nbsp; "
    "Presentation layer only — AI/tracking pipeline unchanged &nbsp;·&nbsp; "
    "Built with Streamlit & Plotly"
    "</div>",
    unsafe_allow_html=True,
)
